version: "3.9"
services:
  pindb:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pinuser
      POSTGRES_PASSWORD: pinpass
      POSTGRES_DB: pindb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  pinserver:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    depends_on:
      - pindb
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - ./server/.env

  pinclient:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    depends_on:
      - pindb
      - server
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./client/.env
volumes:
  postgres-data:
  pgadmin-data:
