version: "3.9"
services:
  pindb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pinuser
      POSTGRES_PASSWORD: pinpass
      POSTGRES_DB: pindb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pincache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  pinserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pindb
      - pincache
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - ./.env
volumes:
  postgres-data:
  pgadmin-data:
  cache:
    driver: local
