version: "3.9"
services:
  pindb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pinuser
      POSTGRES_PASSWORD: pinpass
      POSTGRES_DB: pindb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  pinserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pindb
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - ./.env
volumes:
  postgres-data:
  pgadmin-data:
